name: Rui Zhang Blog
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title
categories: [cpp, java, oop, algorithms, datastructures, multithreading, functionalprogramming, misc]
